@startmindmap
'https://plantuml.com/mindmap-diagram

caption 图1-1
title 学生信息系统功能结构图

* 学生信息系统
** 前端
*** 登录页面
*** 主页面
**** 学生信息页
***** 查询、导出
**** 课程信息页
***** 查询、导出
**** 班级信息页
***** 查询、导出
**** 排课信息页
***** 查询、导出
**** 用户中心页
***** 修改密码
** 后端
*** 登录页面
*** 主页面
**** 学生信息页
***** 增加、查询、修改、删除、导入、导出
**** 课程信息页
***** 增加、查询、修改、删除、导入、导出
**** 班级信息页
***** 增加、查询、修改、删除、导入、导出
**** 排课信息页
***** 增加、查询、修改、删除、导入、导出
**** 操作记录页
***** 查询、导出
**** 管理中心页
***** 导出、重置用户登录密码

@endmindmap
